### ISSUE TITLE
Increase maximum number of objects to be carried by a robot

### ISSUE THREAD

**Issue by frederikhegger** [robocup-at-work/rulebook#17]
or completely eliminate the limit.

**Comment by asadnorouzi** [comment]
I agree with removing the maximum limit for the robot to carry objects!

**Comment by steup** [comment]
I do not agree, because it is a challenge for planning. However I am open for a dynamic limit based on tasks. E.G: 
- BMT 1 Object
- BTT1 2 Object
- BTT3 3 Objects
- Final 5 Objects

It also allows us to create tasks, which are tailored for new teams without a working inventory
If we see major benefits in the large transportation limits, we can remove the limit in the future.

**Comment by asadnorouzi** [comment]
@steup The planning shouldn’t only be based on software but also on hardware design. This is an actual scenario in manufacturing where tools are designed to increase productivity. Removing the limit would enable teams to be innovative to increase their robot’s productivity.

**Comment by deebuls** [comment]
@asadnorouzi and @steup agree with both.

We need to benchmark hardware designing we also need to benchmark planning.

Let the refbox decide how many objects to pick and place? What do you people think?

On a more random thought about the planning problem:
Can the refbox also decide randomly points for each objects ?

**Comment by asadnorouzi** [comment]
I don’t think we should make it more complicated at this stage. Removing the maximum objects to be carried by the robot doesn’t make it more complicated, but opens up more innovative ideas. However, have it randomized by the RefBox makes it more complicated. I disagree to make such complications at this time. I like the idea but maybe we could discuss it for 2021!
