### ISSUE TITLE
Define minimum and maximum of different elements of testbed

### ISSUE THREAD

**Issue by deebuls** [robocup-at-work/rulebook#27]
- Platform heights
- Laser scanner boundary heights
- Objects sizes
- etc

**Comment by asadnorouzi** [comment]
1. Platform range can be between 0cm - 15cm
2. What do you mean by the LIDAR boundary heights?
3. Object sizes are already indicated in the rulebook. Are you referring to the arbitrary objects?

**Comment by steup** [comment]
I completely agree with @debuuls

Laser scanner boundary heights are in my opinion the height of the static arena elements, since these need to be observable by the laser scanners of the robots

Object Size also adheres for the dynamic obstacles used in the arena as well as the barrier tapes / barrier tape areas.

Also Shelf Geomertry and workstations need to be specified especially regarding reflectence and color of sides walls ( or the absence of them)

**Comment by SebastianZug** [comment]
I remember only one situation that made some handicraft work necessary each year - the missing skirt of the round-table, that guarantees a correct detection by laser scanner. Anything else?
