### ISSUE TITLE
Standardize the number, name, schedule and awards for challenges

### ISSUE THREAD

**Issue by deebuls** [robocup-at-work/rulebook#29]
Rather than having new challenges every year, lets standardize to just 3 categories 
1. Navigation challenge
2. Manipulation challenge
3. Perception challenge

We can modify the challenges under these categories every year.
Also fix the scoring of challenges.

**Comment by Pouya-Mansournia** [comment]
Dear committee members
I think @work robot league need some real industrial challenges and I suggest that to change part of the ground and Let's make a bump.  Because many factory floors are not very flat. And another I suggest that make manipulation challenge around of welding robot for example robot and especially arm can do welding challenge with marker and whiteboard maybe this challenges help to us and company manager to use robots in the factory.

**Comment by deebuls** [comment]
Thanks @pouyamansournia  for the feedback. Just to clarify the discussion is towards standardization of the challenges and not defining the challenges(Once this is fixed we can start those discussions). From now on there will always be 3 types of challenges, this helps in :
1. technical committee to select the competition.
2. there is a balance between the challenges (current challenges all require a functional visual component)
3. For the award ceremony since they always know what the categories are.

@robocup-at-work/owners @asadnorouzi  @SebastianZug @steup

**Comment by asadnorouzi** [comment]
@pouyamansournia We can’t change/modify the flooring of the venue. Moreover, as of now, we’re targeting indoor manufacturing where flooring is actually quite standardized and mostly conveniently even.

**Comment by asadnorouzi** [comment]
@deebuls I agree with you on standardizing the challenges. But they must be well defined with an appropriate goal. Do you have anything in mind to propose?

**Comment by SebastianZug** [comment]
In the last years, we defined new types of challenges each year. I agree with @deebuls; we need a midterm strategy here addressing a specific topic. Based on such a general goal refined over some competition seasons, the challenges become more predictable (and consequently more interesting) for our teams.

From my perspective, such a new goal can be defined in the manipulation part only. I propose to introduce **drawers** in our challenge program in order to differ from @home or AmazonLogistics. Open the drawer, look for an object, pick it, and close the drawer.  I know, in this way, we would require additional hardware, and the success entirely depends on the specific setup. But in the first years, we should permit individual settings and define just some basic dimensions. Later we switch the ruleset and integrate arbitrary constructions (very challenging :-) ). Altogether, the new theme:

* documents a topic that is not covered by other RoboCup-leagues 
* valorizes the challenge idea
* makes the activities in the arena more attractive for visitors (the complexity of an in-drawer-grasping-operation is more intuitive)
* generates interesting research questions (I intend to connect more Ph.D. related activities to our league)

**Comment by steup** [comment]
In general I think @deebuls  is right. But I think there are more challenge categories like

- Planning
- Complex Interaction

Planning relates more to finding optimal plans for sub-tasks or orders of sub-tasks 
@SebastianZug proposition is in my opinion a Complex Interaction challenge.

However if we plan to have a single challenges for each category we need to much time and do not have enough competitors in each challenge. Therefore, I think we should select EARLY which challenges we want to do. 2-3 Challenges would be optimal  based on registered teams.  Additionally, we should maybe aim for at least one challenge introducing new stuff to the league and at least one challenge optimizing a very specific sub-goal (Similar to the dexterity etc awards of the rescue league)

The sub-goal optimization challenge can be tackled also by new teams, whereas complex interactions are cool but out of question for newbies.

**Comment by deebuls** [comment]
To conclude everyone agrees that the challenges should be standardized (at least the name). 
The internal test for each topics we can discuss in the subsequent issues we will create for the specific.

So the categories which have been proposed are:
1. Navigation
2. Manipulation
3. Perception
4. Planning
5. Complex Interaction

@SebastianZug  I really like the idea and very novel. Just to be the devil's lawyer the task will propagate research in manipulation and perception but not navigation or planning.  So we have to give some guidelines to the rulebook writers to select on what guidelines we have to select the task.

@steup completely agree no time for doing challenges. Thats why I push for separate arenas for challenges and basic tasks, Let them do the challenges as many times they want, so the teams can run the challenges n number of times as the arena is free and increase their chances.

Again the most important part is what @steup has said it depends on how many teams participate.

**Comment by deebuls** [comment]
I like how this discussion is going but this was not the reason why I started the issue. The reasons I started the issue was:
1. Every year we bring new challenges but teams hardly compete
2. We never get the challenges awards on stage, the reason I think is because its never communicated properly what challenges we are doing and it keeps changing every year.

So the main idea was to standardize the names of the challenges in the rulebook, just the names and not the challenges itself. The challenges will change every year as per discussions but the names the challenges remain same.

So the major discussion I want all of you to think is :
1. How many challenges do we keep? 
2. What should be their generic name?
3. How many should be awarded on stage and how many can be awarded on competition floor?

**Comment by deebuls** [comment]
My answers:
1. 3 (more the better)
2. Technical challenge
3. 1 award on stage for robocup (max winner of all the challenges) + the individual challenge awards we give on the competition floor

**Comment by Pouya-Mansournia** [comment]
It would be better to give three separate award to each technical challenges and go on the stage.

**Comment by deebuls** [comment]
@steup @SebastianZug @asadnorouzi @pouyamansournia  
I have created a new issue #33 for proposing a new challenges and I have rephrased this topic name .

I have also provided different guidelines to consider while writing the challenges. Please review the guidelines and I will send that through the mailing list also.

**Comment by asadnorouzi** [comment]
Following the discussion from the other thread, we could use the overall robot performance as a new technical challenge. This winner would be the robot who has collected the most points throughout the competition. This is given that we decide to make the Final as @deebuls proposed.

In addition to the above, we could introduce 1 or 2 more challenges.

There could be 1 award for the best performance (if we decide to introduce it) and 1 award for the overall of other technical challenges.

**Comment by deebuls** [comment]
> It would be better to give three separate award to each technical challenges and go on the stage.

Its not always possible to get 3 extra awards on stage atleast for robocup because of time constraints and less team participants.
We have 2 options, 1 like the logistics league we do only 1 extra award and give this award on stage.
or like the standard league or rescue league give multiple awards on competition floor.

**Comment by Pouya-Mansournia** [comment]
I like same as rescue league to be given multiple award on competition floor, maybe this action increase league motivation for all participated team tried hard
