### ISSUE TITLE
Making Finals appealing to audience

### ISSUE THREAD

**Issue by deebuls** [robocup-at-work/rulebook#30]
Rather than having the sum of points for deciding the winner can we have the summing up only to decide the 3 finalists and the final points are considered separately.
The finals be run between the top 3 teams of the scoreboard.
A special award can be given to the winner of the table.

Advantages:
1. Since any of the 3 finalists can win it becomes a very uncertain and competitive setup engaging audiences.

**Comment by asadnorouzi** [comment]
Can you elaborate a bit more?

1. What do you mean by “the final points are considered separately”?
2. What do you mean by “A special award can be given to the winner of the table”?

**Comment by steup** [comment]
Last years finals were very nerve wrecking, I think we do not need to add additional tension. However a limitation of competing teams for the finals may be beneficial for the schedule. I think we should be able to decide that on site. And we should put an appropriate section in the rulebook giving the TC/OC on site the capability to do so.

**Comment by deebuls** [comment]
@asadnorouzi I was mentioning that in the finals the 3 finalist start with zero points and the team with maximum points in the finals wins the competition.
As compared to the current winner of the table. 
@asadnorouzi so there are chances when the top of the complete table will not be a winner(as they were second in finals), but we can give them a special award for being top of table
@steup I totally agree its additional tension, but I think that's the reason we go to any competition for example a football match because its uncertain who will win till the last moment. In the current rules sometimes there is team who is top of the table wins because he has more points even though they have a bad finals.

**Comment by asadnorouzi** [comment]
@deebuls Yes, I agree that this would make the Finals more competitive and more exciting for the audience. The results from the Finals can be used to determine the 1st, 2nd, and 3rd ranks. However, we can’t give any special award to the team with highest overall points. Because the RoboCup awards must be standard and defined. The solution to this is to make one of the technical challenges as “overall robot performance” which would be the total points that the robot has collected throughout the competition.

**Comment by steup** [comment]
I can understand your point regardig the tension for the audience. But I am not convinced we should aim that much for the audience. Additionally, I am not convinced this strange rule is easily conveyed to the audience. 
From a team leader persepctive I am completely against it, because it pretty much opens up the title of world champion to be awarded bz chance. Because teams may have hardware failures in the finals or shortly before and therefore end up with 0 points in Finals. And Finals cannot be repeated. Therefore, all our efforts like doing multiple runs of BMT etc. loose their meaning. 
Alternativley, we can award multiplied points  for Finals to enhance the impact, but ignoring the previous results just feels wrong.
With our current schedule, that would also mean, pretty much no one will do challenges before finals, because you cannot risk damaging your robot.

**Comment by deebuls** [comment]
clarifications:
* We dont ignore the other points from tests completely. They are used to determine the top3
* So even in the finals if the top 3 team gets a zero it still will be third prize.
* For audience it will be these are our top teams: The finals is 2 hour between 3 teams.
* With respect to the schedule of the challenges as per discussion in #29 , we should do all the challenges before the finals. Because from the organization perspective doing challenges after finals is not recommended because after finals we have to declare the winners to the award committee.  Therefore I suggest we should run the challenges from day1, multiple times and decide the winner before the finals.  If this means the hardware has to be protected then teams can deal this based on the larger time given to them.
